apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huminex-api-canary
  namespace: huminex
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: api.gethuminex.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: huminex-api
                port:
                  number: 80
