apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huminex-api
  namespace: huminex
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-whitelist: ""
    # For JWT auth integrate oauth2-proxy or auth request endpoint:
    # nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.oauth2.svc.cluster.local/oauth2/auth"
    # nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.gethuminex.com
      secretName: huminex-api-tls
  rules:
    - host: api.gethuminex.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: huminex-api
                port:
                  number: 80
