apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret-provider-class.yaml
  - service.yaml
  - ingress.yaml
  - ingress-canary.yaml
  - analysis-template.yaml
  - rollout.yaml
  - hpa.yaml
