apiVersion: v1
kind: ServiceAccount
metadata:
  name: huminex-api
  namespace: huminex
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: huminex-api-pod-reader
  namespace: huminex
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: huminex-api-pod-reader
  namespace: huminex
subjects:
  - kind: ServiceAccount
    name: huminex-api
    namespace: huminex
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: huminex-api-pod-reader
