apiVersion: v1
kind: Service
metadata:
  name: huminex-api
  namespace: huminex
  labels:
    app: huminex-api
spec:
  type: ClusterIP
  selector:
    app: huminex-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
