apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: rollout-dev-patch.yaml
  - path: analysis-template-dev-patch.yaml
images:
  - name: huminex.azurecr.io/huminex-api
    newName: huminexdevacrohx5ka.azurecr.io/huminex-api
    newTag: 8822edf74669e35175c1168d4ad168530596a214
