apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: rollout-dev-patch.yaml
  - path: analysis-template-dev-patch.yaml
images:
  - name: huminex.azurecr.io/huminex-api
    newName: huminexdevacrohx5ka.azurecr.io/huminex-api
    newTag: 734baf38e602332cd4f6b4f9a67fd331670e3dc0
