apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: rollout-dev-patch.yaml
images:
  - name: huminex.azurecr.io/huminex-api
    newTag: latest
