apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev defaults for internal-only tooling
patches:
  - target:
      kind: Secret
      name: grafana-admin
      namespace: huminex-observability
    patch: |-
      - op: replace
        path: /stringData/admin-password
        value: "huminex-dev-admin"

